// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: pkg/proto/hyper.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DesktopStateResponse_DesktopState int32

const (
	DesktopStateResponse_DESKTOP_STATE_UNKNOWN   DesktopStateResponse_DesktopState = 0
	DesktopStateResponse_DESKTOP_STATE_STARTED   DesktopStateResponse_DesktopState = 1
	DesktopStateResponse_DESKTOP_STATE_STOPPED   DesktopStateResponse_DesktopState = 2
	DesktopStateResponse_DESKTOP_STATE_STOPPING  DesktopStateResponse_DesktopState = 3
	DesktopStateResponse_DESKTOP_STATE_PAUSED    DesktopStateResponse_DesktopState = 4
	DesktopStateResponse_DESKTOP_STATE_SUSPENDED DesktopStateResponse_DesktopState = 5
	DesktopStateResponse_DESKTOP_STATE_BLOCKED   DesktopStateResponse_DesktopState = 6
	DesktopStateResponse_DESKTOP_STATE_CRASHED   DesktopStateResponse_DesktopState = 7
	DesktopStateResponse_DESKTOP_STATE_NOSTATE   DesktopStateResponse_DesktopState = 8
)

// Enum value maps for DesktopStateResponse_DesktopState.
var (
	DesktopStateResponse_DesktopState_name = map[int32]string{
		0: "DESKTOP_STATE_UNKNOWN",
		1: "DESKTOP_STATE_STARTED",
		2: "DESKTOP_STATE_STOPPED",
		3: "DESKTOP_STATE_STOPPING",
		4: "DESKTOP_STATE_PAUSED",
		5: "DESKTOP_STATE_SUSPENDED",
		6: "DESKTOP_STATE_BLOCKED",
		7: "DESKTOP_STATE_CRASHED",
		8: "DESKTOP_STATE_NOSTATE",
	}
	DesktopStateResponse_DesktopState_value = map[string]int32{
		"DESKTOP_STATE_UNKNOWN":   0,
		"DESKTOP_STATE_STARTED":   1,
		"DESKTOP_STATE_STOPPED":   2,
		"DESKTOP_STATE_STOPPING":  3,
		"DESKTOP_STATE_PAUSED":    4,
		"DESKTOP_STATE_SUSPENDED": 5,
		"DESKTOP_STATE_BLOCKED":   6,
		"DESKTOP_STATE_CRASHED":   7,
		"DESKTOP_STATE_NOSTATE":   8,
	}
)

func (x DesktopStateResponse_DesktopState) Enum() *DesktopStateResponse_DesktopState {
	p := new(DesktopStateResponse_DesktopState)
	*p = x
	return p
}

func (x DesktopStateResponse_DesktopState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesktopStateResponse_DesktopState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_hyper_proto_enumTypes[0].Descriptor()
}

func (DesktopStateResponse_DesktopState) Type() protoreflect.EnumType {
	return &file_pkg_proto_hyper_proto_enumTypes[0]
}

func (x DesktopStateResponse_DesktopState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesktopStateResponse_DesktopState.Descriptor instead.
func (DesktopStateResponse_DesktopState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{5, 0}
}

type DesktopStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xml string `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
}

func (x *DesktopStartRequest) Reset() {
	*x = DesktopStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartRequest) ProtoMessage() {}

func (x *DesktopStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartRequest.ProtoReflect.Descriptor instead.
func (*DesktopStartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{0}
}

func (x *DesktopStartRequest) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

type DesktopStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xml string `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
}

func (x *DesktopStartResponse) Reset() {
	*x = DesktopStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStartResponse) ProtoMessage() {}

func (x *DesktopStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStartResponse.ProtoReflect.Descriptor instead.
func (*DesktopStartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{1}
}

func (x *DesktopStartResponse) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

type DesktopStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DesktopStopRequest) Reset() {
	*x = DesktopStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStopRequest) ProtoMessage() {}

func (x *DesktopStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStopRequest.ProtoReflect.Descriptor instead.
func (*DesktopStopRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{2}
}

func (x *DesktopStopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DesktopStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopStopResponse) Reset() {
	*x = DesktopStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStopResponse) ProtoMessage() {}

func (x *DesktopStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStopResponse.ProtoReflect.Descriptor instead.
func (*DesktopStopResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{3}
}

type DesktopStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DesktopStateRequest) Reset() {
	*x = DesktopStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStateRequest) ProtoMessage() {}

func (x *DesktopStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStateRequest.ProtoReflect.Descriptor instead.
func (*DesktopStateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{4}
}

func (x *DesktopStateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DesktopStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State DesktopStateResponse_DesktopState `protobuf:"varint,1,opt,name=state,proto3,enum=proto.DesktopStateResponse_DesktopState" json:"state,omitempty"`
}

func (x *DesktopStateResponse) Reset() {
	*x = DesktopStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopStateResponse) ProtoMessage() {}

func (x *DesktopStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopStateResponse.ProtoReflect.Descriptor instead.
func (*DesktopStateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{5}
}

func (x *DesktopStateResponse) GetState() DesktopStateResponse_DesktopState {
	if x != nil {
		return x.State
	}
	return DesktopStateResponse_DESKTOP_STATE_UNKNOWN
}

type DesktopValidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xml string `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
}

func (x *DesktopValidateRequest) Reset() {
	*x = DesktopValidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopValidateRequest) ProtoMessage() {}

func (x *DesktopValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopValidateRequest.ProtoReflect.Descriptor instead.
func (*DesktopValidateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{6}
}

func (x *DesktopValidateRequest) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

type DesktopValidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopValidateResponse) Reset() {
	*x = DesktopValidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopValidateResponse) ProtoMessage() {}

func (x *DesktopValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopValidateResponse.ProtoReflect.Descriptor instead.
func (*DesktopValidateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{7}
}

type DesktopSuspendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DesktopSuspendRequest) Reset() {
	*x = DesktopSuspendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopSuspendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopSuspendRequest) ProtoMessage() {}

func (x *DesktopSuspendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopSuspendRequest.ProtoReflect.Descriptor instead.
func (*DesktopSuspendRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{8}
}

func (x *DesktopSuspendRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DesktopSuspendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopSuspendResponse) Reset() {
	*x = DesktopSuspendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopSuspendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopSuspendResponse) ProtoMessage() {}

func (x *DesktopSuspendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopSuspendResponse.ProtoReflect.Descriptor instead.
func (*DesktopSuspendResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{9}
}

type DesktopResumeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DesktopResumeRequest) Reset() {
	*x = DesktopResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopResumeRequest) ProtoMessage() {}

func (x *DesktopResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopResumeRequest.ProtoReflect.Descriptor instead.
func (*DesktopResumeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{10}
}

func (x *DesktopResumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DesktopResumeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopResumeResponse) Reset() {
	*x = DesktopResumeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopResumeResponse) ProtoMessage() {}

func (x *DesktopResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopResumeResponse.ProtoReflect.Descriptor instead.
func (*DesktopResumeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{11}
}

type DesktopSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *DesktopSaveRequest) Reset() {
	*x = DesktopSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopSaveRequest) ProtoMessage() {}

func (x *DesktopSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopSaveRequest.ProtoReflect.Descriptor instead.
func (*DesktopSaveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{12}
}

func (x *DesktopSaveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DesktopSaveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DesktopSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopSaveResponse) Reset() {
	*x = DesktopSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopSaveResponse) ProtoMessage() {}

func (x *DesktopSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopSaveResponse.ProtoReflect.Descriptor instead.
func (*DesktopSaveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{13}
}

type DesktopRestoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *DesktopRestoreRequest) Reset() {
	*x = DesktopRestoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopRestoreRequest) ProtoMessage() {}

func (x *DesktopRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopRestoreRequest.ProtoReflect.Descriptor instead.
func (*DesktopRestoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{14}
}

func (x *DesktopRestoreRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DesktopRestoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopRestoreResponse) Reset() {
	*x = DesktopRestoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopRestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopRestoreResponse) ProtoMessage() {}

func (x *DesktopRestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopRestoreResponse.ProtoReflect.Descriptor instead.
func (*DesktopRestoreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{15}
}

type DesktopListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopListRequest) Reset() {
	*x = DesktopListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopListRequest) ProtoMessage() {}

func (x *DesktopListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopListRequest.ProtoReflect.Descriptor instead.
func (*DesktopListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{16}
}

type DesktopListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DesktopListResponse) Reset() {
	*x = DesktopListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopListResponse) ProtoMessage() {}

func (x *DesktopListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopListResponse.ProtoReflect.Descriptor instead.
func (*DesktopListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{17}
}

func (x *DesktopListResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DesktopXMLGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DesktopXMLGetRequest) Reset() {
	*x = DesktopXMLGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopXMLGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopXMLGetRequest) ProtoMessage() {}

func (x *DesktopXMLGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopXMLGetRequest.ProtoReflect.Descriptor instead.
func (*DesktopXMLGetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{18}
}

func (x *DesktopXMLGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DesktopXMLGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xml string `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
}

func (x *DesktopXMLGetResponse) Reset() {
	*x = DesktopXMLGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopXMLGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopXMLGetResponse) ProtoMessage() {}

func (x *DesktopXMLGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopXMLGetResponse.ProtoReflect.Descriptor instead.
func (*DesktopXMLGetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{19}
}

func (x *DesktopXMLGetResponse) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

type DesktopMigrateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hyper string `protobuf:"bytes,2,opt,name=hyper,proto3" json:"hyper,omitempty"`
}

func (x *DesktopMigrateRequest) Reset() {
	*x = DesktopMigrateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopMigrateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopMigrateRequest) ProtoMessage() {}

func (x *DesktopMigrateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopMigrateRequest.ProtoReflect.Descriptor instead.
func (*DesktopMigrateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{20}
}

func (x *DesktopMigrateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DesktopMigrateRequest) GetHyper() string {
	if x != nil {
		return x.Hyper
	}
	return ""
}

type DesktopMigrateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DesktopMigrateResponse) Reset() {
	*x = DesktopMigrateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_hyper_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DesktopMigrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopMigrateResponse) ProtoMessage() {}

func (x *DesktopMigrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_hyper_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopMigrateResponse.ProtoReflect.Descriptor instead.
func (*DesktopMigrateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_hyper_proto_rawDescGZIP(), []int{21}
}

var File_pkg_proto_hyper_proto protoreflect.FileDescriptor

var file_pkg_proto_hyper_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x79, 0x70, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27,
	0x0a, 0x13, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x78, 0x6d, 0x6c, 0x22, 0x28, 0x0a, 0x14, 0x44, 0x65, 0x73, 0x6b, 0x74,
	0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x78, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x78, 0x6d,
	0x6c, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x6f, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x73, 0x6b, 0x74,
	0x6f, 0x70, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25,
	0x0a, 0x13, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xdc, 0x02, 0x0a, 0x14, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74,
	0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x83,
	0x02, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x19, 0x0a, 0x15, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x45,
	0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52,
	0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x1a, 0x0a, 0x16, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14,
	0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x41,
	0x55, 0x53, 0x45, 0x44, 0x10, 0x04, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f,
	0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x55, 0x53, 0x50, 0x45, 0x4e, 0x44, 0x45,
	0x44, 0x10, 0x05, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x06, 0x12, 0x19,
	0x0a, 0x15, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x43, 0x52, 0x41, 0x53, 0x48, 0x45, 0x44, 0x10, 0x07, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x45, 0x53,
	0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4e, 0x4f, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x10, 0x08, 0x22, 0x2a, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x78, 0x6d, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x78, 0x6d, 0x6c,
	0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53,
	0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26,
	0x0a, 0x14, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x38, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2b, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x18, 0x0a,
	0x16, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x6b, 0x74,
	0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x27, 0x0a,
	0x13, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x58, 0x4d, 0x4c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29,
	0x0a, 0x15, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x58, 0x4d, 0x4c, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x78, 0x6d, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x78, 0x6d, 0x6c, 0x22, 0x3d, 0x0a, 0x15, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x79, 0x70, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x68, 0x79, 0x70, 0x65, 0x72, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xd8, 0x06, 0x0a, 0x05, 0x48, 0x79, 0x70, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x0c,
	0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x6b, 0x74,
	0x6f, 0x70, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x49, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0f, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f,
	0x0a, 0x0e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64,
	0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x53, 0x75, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x75,
	0x73, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4c, 0x0a, 0x0d, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a,
	0x0b, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x61, 0x76, 0x65, 0x12, 0x19, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x61, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0d, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x58, 0x4d, 0x4c, 0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x58, 0x4d, 0x4c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x58, 0x4d, 0x4c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e,
	0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2c, 0x5a,
	0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x73, 0x61, 0x72,
	0x64, 0x2d, 0x76, 0x64, 0x69, 0x2f, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2f, 0x68, 0x79, 0x70, 0x65,
	0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_hyper_proto_rawDescOnce sync.Once
	file_pkg_proto_hyper_proto_rawDescData = file_pkg_proto_hyper_proto_rawDesc
)

func file_pkg_proto_hyper_proto_rawDescGZIP() []byte {
	file_pkg_proto_hyper_proto_rawDescOnce.Do(func() {
		file_pkg_proto_hyper_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_hyper_proto_rawDescData)
	})
	return file_pkg_proto_hyper_proto_rawDescData
}

var file_pkg_proto_hyper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_hyper_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pkg_proto_hyper_proto_goTypes = []interface{}{
	(DesktopStateResponse_DesktopState)(0), // 0: proto.DesktopStateResponse.DesktopState
	(*DesktopStartRequest)(nil),            // 1: proto.DesktopStartRequest
	(*DesktopStartResponse)(nil),           // 2: proto.DesktopStartResponse
	(*DesktopStopRequest)(nil),             // 3: proto.DesktopStopRequest
	(*DesktopStopResponse)(nil),            // 4: proto.DesktopStopResponse
	(*DesktopStateRequest)(nil),            // 5: proto.DesktopStateRequest
	(*DesktopStateResponse)(nil),           // 6: proto.DesktopStateResponse
	(*DesktopValidateRequest)(nil),         // 7: proto.DesktopValidateRequest
	(*DesktopValidateResponse)(nil),        // 8: proto.DesktopValidateResponse
	(*DesktopSuspendRequest)(nil),          // 9: proto.DesktopSuspendRequest
	(*DesktopSuspendResponse)(nil),         // 10: proto.DesktopSuspendResponse
	(*DesktopResumeRequest)(nil),           // 11: proto.DesktopResumeRequest
	(*DesktopResumeResponse)(nil),          // 12: proto.DesktopResumeResponse
	(*DesktopSaveRequest)(nil),             // 13: proto.DesktopSaveRequest
	(*DesktopSaveResponse)(nil),            // 14: proto.DesktopSaveResponse
	(*DesktopRestoreRequest)(nil),          // 15: proto.DesktopRestoreRequest
	(*DesktopRestoreResponse)(nil),         // 16: proto.DesktopRestoreResponse
	(*DesktopListRequest)(nil),             // 17: proto.DesktopListRequest
	(*DesktopListResponse)(nil),            // 18: proto.DesktopListResponse
	(*DesktopXMLGetRequest)(nil),           // 19: proto.DesktopXMLGetRequest
	(*DesktopXMLGetResponse)(nil),          // 20: proto.DesktopXMLGetResponse
	(*DesktopMigrateRequest)(nil),          // 21: proto.DesktopMigrateRequest
	(*DesktopMigrateResponse)(nil),         // 22: proto.DesktopMigrateResponse
}
var file_pkg_proto_hyper_proto_depIdxs = []int32{
	0,  // 0: proto.DesktopStateResponse.state:type_name -> proto.DesktopStateResponse.DesktopState
	1,  // 1: proto.Hyper.DesktopStart:input_type -> proto.DesktopStartRequest
	3,  // 2: proto.Hyper.DesktopStop:input_type -> proto.DesktopStopRequest
	5,  // 3: proto.Hyper.DesktopState:input_type -> proto.DesktopStateRequest
	7,  // 4: proto.Hyper.DesktopValidate:input_type -> proto.DesktopValidateRequest
	9,  // 5: proto.Hyper.DesktopSuspend:input_type -> proto.DesktopSuspendRequest
	11, // 6: proto.Hyper.DesktopResume:input_type -> proto.DesktopResumeRequest
	13, // 7: proto.Hyper.DesktopSave:input_type -> proto.DesktopSaveRequest
	15, // 8: proto.Hyper.DesktopRestore:input_type -> proto.DesktopRestoreRequest
	19, // 9: proto.Hyper.DesktopXMLGet:input_type -> proto.DesktopXMLGetRequest
	17, // 10: proto.Hyper.DesktopList:input_type -> proto.DesktopListRequest
	21, // 11: proto.Hyper.DesktopMigrate:input_type -> proto.DesktopMigrateRequest
	2,  // 12: proto.Hyper.DesktopStart:output_type -> proto.DesktopStartResponse
	4,  // 13: proto.Hyper.DesktopStop:output_type -> proto.DesktopStopResponse
	6,  // 14: proto.Hyper.DesktopState:output_type -> proto.DesktopStateResponse
	8,  // 15: proto.Hyper.DesktopValidate:output_type -> proto.DesktopValidateResponse
	10, // 16: proto.Hyper.DesktopSuspend:output_type -> proto.DesktopSuspendResponse
	12, // 17: proto.Hyper.DesktopResume:output_type -> proto.DesktopResumeResponse
	14, // 18: proto.Hyper.DesktopSave:output_type -> proto.DesktopSaveResponse
	16, // 19: proto.Hyper.DesktopRestore:output_type -> proto.DesktopRestoreResponse
	20, // 20: proto.Hyper.DesktopXMLGet:output_type -> proto.DesktopXMLGetResponse
	18, // 21: proto.Hyper.DesktopList:output_type -> proto.DesktopListResponse
	22, // 22: proto.Hyper.DesktopMigrate:output_type -> proto.DesktopMigrateResponse
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_hyper_proto_init() }
func file_pkg_proto_hyper_proto_init() {
	if File_pkg_proto_hyper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_hyper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopValidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopValidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopSuspendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopSuspendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopResumeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopRestoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopRestoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopXMLGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopXMLGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopMigrateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_hyper_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DesktopMigrateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_hyper_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_hyper_proto_goTypes,
		DependencyIndexes: file_pkg_proto_hyper_proto_depIdxs,
		EnumInfos:         file_pkg_proto_hyper_proto_enumTypes,
		MessageInfos:      file_pkg_proto_hyper_proto_msgTypes,
	}.Build()
	File_pkg_proto_hyper_proto = out.File
	file_pkg_proto_hyper_proto_rawDesc = nil
	file_pkg_proto_hyper_proto_goTypes = nil
	file_pkg_proto_hyper_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HyperClient is the client API for Hyper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HyperClient interface {
	DesktopStart(ctx context.Context, in *DesktopStartRequest, opts ...grpc.CallOption) (*DesktopStartResponse, error)
	DesktopStop(ctx context.Context, in *DesktopStopRequest, opts ...grpc.CallOption) (*DesktopStopResponse, error)
	DesktopState(ctx context.Context, in *DesktopStateRequest, opts ...grpc.CallOption) (*DesktopStateResponse, error)
	DesktopValidate(ctx context.Context, in *DesktopValidateRequest, opts ...grpc.CallOption) (*DesktopValidateResponse, error)
	DesktopSuspend(ctx context.Context, in *DesktopSuspendRequest, opts ...grpc.CallOption) (*DesktopSuspendResponse, error)
	DesktopResume(ctx context.Context, in *DesktopResumeRequest, opts ...grpc.CallOption) (*DesktopResumeResponse, error)
	DesktopSave(ctx context.Context, in *DesktopSaveRequest, opts ...grpc.CallOption) (*DesktopSaveResponse, error)
	DesktopRestore(ctx context.Context, in *DesktopRestoreRequest, opts ...grpc.CallOption) (*DesktopRestoreResponse, error)
	DesktopXMLGet(ctx context.Context, in *DesktopXMLGetRequest, opts ...grpc.CallOption) (*DesktopXMLGetResponse, error)
	DesktopList(ctx context.Context, in *DesktopListRequest, opts ...grpc.CallOption) (*DesktopListResponse, error)
	DesktopMigrate(ctx context.Context, in *DesktopMigrateRequest, opts ...grpc.CallOption) (*DesktopMigrateResponse, error)
}

type hyperClient struct {
	cc grpc.ClientConnInterface
}

func NewHyperClient(cc grpc.ClientConnInterface) HyperClient {
	return &hyperClient{cc}
}

func (c *hyperClient) DesktopStart(ctx context.Context, in *DesktopStartRequest, opts ...grpc.CallOption) (*DesktopStartResponse, error) {
	out := new(DesktopStartResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) DesktopStop(ctx context.Context, in *DesktopStopRequest, opts ...grpc.CallOption) (*DesktopStopResponse, error) {
	out := new(DesktopStopResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopStop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) DesktopState(ctx context.Context, in *DesktopStateRequest, opts ...grpc.CallOption) (*DesktopStateResponse, error) {
	out := new(DesktopStateResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) DesktopValidate(ctx context.Context, in *DesktopValidateRequest, opts ...grpc.CallOption) (*DesktopValidateResponse, error) {
	out := new(DesktopValidateResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopValidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) DesktopSuspend(ctx context.Context, in *DesktopSuspendRequest, opts ...grpc.CallOption) (*DesktopSuspendResponse, error) {
	out := new(DesktopSuspendResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopSuspend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) DesktopResume(ctx context.Context, in *DesktopResumeRequest, opts ...grpc.CallOption) (*DesktopResumeResponse, error) {
	out := new(DesktopResumeResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopResume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) DesktopSave(ctx context.Context, in *DesktopSaveRequest, opts ...grpc.CallOption) (*DesktopSaveResponse, error) {
	out := new(DesktopSaveResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) DesktopRestore(ctx context.Context, in *DesktopRestoreRequest, opts ...grpc.CallOption) (*DesktopRestoreResponse, error) {
	out := new(DesktopRestoreResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopRestore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) DesktopXMLGet(ctx context.Context, in *DesktopXMLGetRequest, opts ...grpc.CallOption) (*DesktopXMLGetResponse, error) {
	out := new(DesktopXMLGetResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopXMLGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) DesktopList(ctx context.Context, in *DesktopListRequest, opts ...grpc.CallOption) (*DesktopListResponse, error) {
	out := new(DesktopListResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) DesktopMigrate(ctx context.Context, in *DesktopMigrateRequest, opts ...grpc.CallOption) (*DesktopMigrateResponse, error) {
	out := new(DesktopMigrateResponse)
	err := c.cc.Invoke(ctx, "/proto.Hyper/DesktopMigrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HyperServer is the server API for Hyper service.
type HyperServer interface {
	DesktopStart(context.Context, *DesktopStartRequest) (*DesktopStartResponse, error)
	DesktopStop(context.Context, *DesktopStopRequest) (*DesktopStopResponse, error)
	DesktopState(context.Context, *DesktopStateRequest) (*DesktopStateResponse, error)
	DesktopValidate(context.Context, *DesktopValidateRequest) (*DesktopValidateResponse, error)
	DesktopSuspend(context.Context, *DesktopSuspendRequest) (*DesktopSuspendResponse, error)
	DesktopResume(context.Context, *DesktopResumeRequest) (*DesktopResumeResponse, error)
	DesktopSave(context.Context, *DesktopSaveRequest) (*DesktopSaveResponse, error)
	DesktopRestore(context.Context, *DesktopRestoreRequest) (*DesktopRestoreResponse, error)
	DesktopXMLGet(context.Context, *DesktopXMLGetRequest) (*DesktopXMLGetResponse, error)
	DesktopList(context.Context, *DesktopListRequest) (*DesktopListResponse, error)
	DesktopMigrate(context.Context, *DesktopMigrateRequest) (*DesktopMigrateResponse, error)
}

// UnimplementedHyperServer can be embedded to have forward compatible implementations.
type UnimplementedHyperServer struct {
}

func (*UnimplementedHyperServer) DesktopStart(context.Context, *DesktopStartRequest) (*DesktopStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopStart not implemented")
}
func (*UnimplementedHyperServer) DesktopStop(context.Context, *DesktopStopRequest) (*DesktopStopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopStop not implemented")
}
func (*UnimplementedHyperServer) DesktopState(context.Context, *DesktopStateRequest) (*DesktopStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopState not implemented")
}
func (*UnimplementedHyperServer) DesktopValidate(context.Context, *DesktopValidateRequest) (*DesktopValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopValidate not implemented")
}
func (*UnimplementedHyperServer) DesktopSuspend(context.Context, *DesktopSuspendRequest) (*DesktopSuspendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopSuspend not implemented")
}
func (*UnimplementedHyperServer) DesktopResume(context.Context, *DesktopResumeRequest) (*DesktopResumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopResume not implemented")
}
func (*UnimplementedHyperServer) DesktopSave(context.Context, *DesktopSaveRequest) (*DesktopSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopSave not implemented")
}
func (*UnimplementedHyperServer) DesktopRestore(context.Context, *DesktopRestoreRequest) (*DesktopRestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopRestore not implemented")
}
func (*UnimplementedHyperServer) DesktopXMLGet(context.Context, *DesktopXMLGetRequest) (*DesktopXMLGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopXMLGet not implemented")
}
func (*UnimplementedHyperServer) DesktopList(context.Context, *DesktopListRequest) (*DesktopListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopList not implemented")
}
func (*UnimplementedHyperServer) DesktopMigrate(context.Context, *DesktopMigrateRequest) (*DesktopMigrateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DesktopMigrate not implemented")
}

func RegisterHyperServer(s *grpc.Server, srv HyperServer) {
	s.RegisterService(&_Hyper_serviceDesc, srv)
}

func _Hyper_DesktopStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopStart(ctx, req.(*DesktopStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_DesktopStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopStop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopStop(ctx, req.(*DesktopStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_DesktopState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopState(ctx, req.(*DesktopStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_DesktopValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopValidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopValidate(ctx, req.(*DesktopValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_DesktopSuspend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopSuspendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopSuspend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopSuspend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopSuspend(ctx, req.(*DesktopSuspendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_DesktopResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopResume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopResume(ctx, req.(*DesktopResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_DesktopSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopSave(ctx, req.(*DesktopSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_DesktopRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopRestore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopRestore(ctx, req.(*DesktopRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_DesktopXMLGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopXMLGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopXMLGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopXMLGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopXMLGet(ctx, req.(*DesktopXMLGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_DesktopList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopList(ctx, req.(*DesktopListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_DesktopMigrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopMigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).DesktopMigrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hyper/DesktopMigrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).DesktopMigrate(ctx, req.(*DesktopMigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hyper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Hyper",
	HandlerType: (*HyperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DesktopStart",
			Handler:    _Hyper_DesktopStart_Handler,
		},
		{
			MethodName: "DesktopStop",
			Handler:    _Hyper_DesktopStop_Handler,
		},
		{
			MethodName: "DesktopState",
			Handler:    _Hyper_DesktopState_Handler,
		},
		{
			MethodName: "DesktopValidate",
			Handler:    _Hyper_DesktopValidate_Handler,
		},
		{
			MethodName: "DesktopSuspend",
			Handler:    _Hyper_DesktopSuspend_Handler,
		},
		{
			MethodName: "DesktopResume",
			Handler:    _Hyper_DesktopResume_Handler,
		},
		{
			MethodName: "DesktopSave",
			Handler:    _Hyper_DesktopSave_Handler,
		},
		{
			MethodName: "DesktopRestore",
			Handler:    _Hyper_DesktopRestore_Handler,
		},
		{
			MethodName: "DesktopXMLGet",
			Handler:    _Hyper_DesktopXMLGet_Handler,
		},
		{
			MethodName: "DesktopList",
			Handler:    _Hyper_DesktopList_Handler,
		},
		{
			MethodName: "DesktopMigrate",
			Handler:    _Hyper_DesktopMigrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/hyper.proto",
}
