# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engine/grpc/proto/domains_stream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='engine/grpc/proto/domains_stream.proto',
  package='changes',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&engine/grpc/proto/domains_stream.proto\x12\x07\x63hanges\"\xca\x01\n\x06Viewer\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x19\n\x11hostname_external\x18\x02 \x01(\t\x12\x12\n\nport_spice\x18\x05 \x01(\x05\x12\x16\n\x0eport_spice_ssl\x18\x06 \x01(\x05\x12\x10\n\x08port_vnc\x18\x07 \x01(\x05\x12\x1a\n\x12port_vnc_websocket\x18\x08 \x01(\x05\x12\x0e\n\x06passwd\x18\t \x01(\t\x12\x13\n\x0b\x63lient_addr\x18\n \x01(\t\x12\x14\n\x0c\x63lient_since\x18\x0b \x01(\x02\"\x16\n\x14\x44omainsStreamRequest\"\xfc\x01\n\x15\x44omainsStreamResponse\x12\x11\n\tdomain_id\x18\x01 \x01(\t\x12\x33\n\x05state\x18\x02 \x01(\x0e\x32$.changes.DomainsStreamResponse.State\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12\x0c\n\x04kind\x18\x04 \x01(\t\x12\x14\n\x0cnext_actions\x18\x05 \x03(\t\x12\x1f\n\x06viewer\x18\x06 \x01(\x0b\x32\x0f.changes.Viewer\"F\n\x05State\x12\x0b\n\x07STARTED\x10\x00\x12\x0b\n\x07STOPPED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x12\x0b\n\x07UNKNOWN\x10\x03\x12\n\n\x06PAUSED\x10\x04\x32]\n\rDomainsStream\x12L\n\x07\x43hanges\x12\x1d.changes.DomainsStreamRequest\x1a\x1e.changes.DomainsStreamResponse\"\x00\x30\x01\x62\x06proto3')
)



_DOMAINSSTREAMRESPONSE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='changes.DomainsStreamResponse.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STARTED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOPPED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAUSED', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=463,
  serialized_end=533,
)
_sym_db.RegisterEnumDescriptor(_DOMAINSSTREAMRESPONSE_STATE)


_VIEWER = _descriptor.Descriptor(
  name='Viewer',
  full_name='changes.Viewer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hostname', full_name='changes.Viewer.hostname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hostname_external', full_name='changes.Viewer.hostname_external', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port_spice', full_name='changes.Viewer.port_spice', index=2,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port_spice_ssl', full_name='changes.Viewer.port_spice_ssl', index=3,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port_vnc', full_name='changes.Viewer.port_vnc', index=4,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port_vnc_websocket', full_name='changes.Viewer.port_vnc_websocket', index=5,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passwd', full_name='changes.Viewer.passwd', index=6,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_addr', full_name='changes.Viewer.client_addr', index=7,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_since', full_name='changes.Viewer.client_since', index=8,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=254,
)


_DOMAINSSTREAMREQUEST = _descriptor.Descriptor(
  name='DomainsStreamRequest',
  full_name='changes.DomainsStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=278,
)


_DOMAINSSTREAMRESPONSE = _descriptor.Descriptor(
  name='DomainsStreamResponse',
  full_name='changes.DomainsStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain_id', full_name='changes.DomainsStreamResponse.domain_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='changes.DomainsStreamResponse.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detail', full_name='changes.DomainsStreamResponse.detail', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='changes.DomainsStreamResponse.kind', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_actions', full_name='changes.DomainsStreamResponse.next_actions', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='viewer', full_name='changes.DomainsStreamResponse.viewer', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DOMAINSSTREAMRESPONSE_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=533,
)

_DOMAINSSTREAMRESPONSE.fields_by_name['state'].enum_type = _DOMAINSSTREAMRESPONSE_STATE
_DOMAINSSTREAMRESPONSE.fields_by_name['viewer'].message_type = _VIEWER
_DOMAINSSTREAMRESPONSE_STATE.containing_type = _DOMAINSSTREAMRESPONSE
DESCRIPTOR.message_types_by_name['Viewer'] = _VIEWER
DESCRIPTOR.message_types_by_name['DomainsStreamRequest'] = _DOMAINSSTREAMREQUEST
DESCRIPTOR.message_types_by_name['DomainsStreamResponse'] = _DOMAINSSTREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Viewer = _reflection.GeneratedProtocolMessageType('Viewer', (_message.Message,), dict(
  DESCRIPTOR = _VIEWER,
  __module__ = 'engine.grpc.proto.domains_stream_pb2'
  # @@protoc_insertion_point(class_scope:changes.Viewer)
  ))
_sym_db.RegisterMessage(Viewer)

DomainsStreamRequest = _reflection.GeneratedProtocolMessageType('DomainsStreamRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOMAINSSTREAMREQUEST,
  __module__ = 'engine.grpc.proto.domains_stream_pb2'
  # @@protoc_insertion_point(class_scope:changes.DomainsStreamRequest)
  ))
_sym_db.RegisterMessage(DomainsStreamRequest)

DomainsStreamResponse = _reflection.GeneratedProtocolMessageType('DomainsStreamResponse', (_message.Message,), dict(
  DESCRIPTOR = _DOMAINSSTREAMRESPONSE,
  __module__ = 'engine.grpc.proto.domains_stream_pb2'
  # @@protoc_insertion_point(class_scope:changes.DomainsStreamResponse)
  ))
_sym_db.RegisterMessage(DomainsStreamResponse)



_DOMAINSSTREAM = _descriptor.ServiceDescriptor(
  name='DomainsStream',
  full_name='changes.DomainsStream',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=535,
  serialized_end=628,
  methods=[
  _descriptor.MethodDescriptor(
    name='Changes',
    full_name='changes.DomainsStream.Changes',
    index=0,
    containing_service=None,
    input_type=_DOMAINSSTREAMREQUEST,
    output_type=_DOMAINSSTREAMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOMAINSSTREAM)

DESCRIPTOR.services_by_name['DomainsStream'] = _DOMAINSSTREAM

# @@protoc_insertion_point(module_scope)
