# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from engine.grpc.proto import engine_pb2 as engine_dot_grpc_dot_proto_dot_engine__pb2


class EngineStub(object):
  """import "google/protobuf/empty.proto"; 
  import "google/protobuf/any.proto";

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.IsAlive = channel.unary_unary(
        '/engine.Engine/IsAlive',
        request_serializer=engine_dot_grpc_dot_proto_dot_engine__pb2.IsAliveRequest.SerializeToString,
        response_deserializer=engine_dot_grpc_dot_proto_dot_engine__pb2.IsAliveResponse.FromString,
        )
    self.Status = channel.unary_unary(
        '/engine.Engine/Status',
        request_serializer=engine_dot_grpc_dot_proto_dot_engine__pb2.StatusRequest.SerializeToString,
        response_deserializer=engine_dot_grpc_dot_proto_dot_engine__pb2.StatusResponse.FromString,
        )
    self.Config = channel.unary_unary(
        '/engine.Engine/Config',
        request_serializer=engine_dot_grpc_dot_proto_dot_engine__pb2.ConfigRequest.SerializeToString,
        response_deserializer=engine_dot_grpc_dot_proto_dot_engine__pb2.ConfigResponse.FromString,
        )


class EngineServicer(object):
  """import "google/protobuf/empty.proto"; 
  import "google/protobuf/any.proto";

  """

  def IsAlive(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Status(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Config(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EngineServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'IsAlive': grpc.unary_unary_rpc_method_handler(
          servicer.IsAlive,
          request_deserializer=engine_dot_grpc_dot_proto_dot_engine__pb2.IsAliveRequest.FromString,
          response_serializer=engine_dot_grpc_dot_proto_dot_engine__pb2.IsAliveResponse.SerializeToString,
      ),
      'Status': grpc.unary_unary_rpc_method_handler(
          servicer.Status,
          request_deserializer=engine_dot_grpc_dot_proto_dot_engine__pb2.StatusRequest.FromString,
          response_serializer=engine_dot_grpc_dot_proto_dot_engine__pb2.StatusResponse.SerializeToString,
      ),
      'Config': grpc.unary_unary_rpc_method_handler(
          servicer.Config,
          request_deserializer=engine_dot_grpc_dot_proto_dot_engine__pb2.ConfigRequest.FromString,
          response_serializer=engine_dot_grpc_dot_proto_dot_engine__pb2.ConfigResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'engine.Engine', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
