# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from engine.grpc.proto import templates_pb2 as engine_dot_grpc_dot_proto_dot_templates__pb2


class TemplatesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TemplateGet = channel.unary_unary(
        '/templates.Templates/TemplateGet',
        request_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateGetRequest.SerializeToString,
        response_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateGetResponse.FromString,
        )
    self.TemplateList = channel.unary_unary(
        '/templates.Templates/TemplateList',
        request_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateListRequest.SerializeToString,
        response_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateListResponse.FromString,
        )
    self.TemplateDelete = channel.unary_unary(
        '/templates.Templates/TemplateDelete',
        request_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateDeleteRequest.SerializeToString,
        response_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateDeleteResponse.FromString,
        )
    self.TemplateUpdate = channel.unary_unary(
        '/templates.Templates/TemplateUpdate',
        request_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateUpdateRequest.SerializeToString,
        response_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateUpdateResponse.FromString,
        )
    self.TemplateFromDesktop = channel.unary_unary(
        '/templates.Templates/TemplateFromDesktop',
        request_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateFromDesktopRequest.SerializeToString,
        response_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateFromDesktopResponse.FromString,
        )
    self.BaseGet = channel.unary_unary(
        '/templates.Templates/BaseGet',
        request_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.BaseGetRequest.SerializeToString,
        response_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.BaseGetResponse.FromString,
        )
    self.BaseList = channel.unary_unary(
        '/templates.Templates/BaseList',
        request_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.BaseListRequest.SerializeToString,
        response_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.BaseListResponse.FromString,
        )


class TemplatesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TemplateGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TemplateList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TemplateDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TemplateUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TemplateFromDesktop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BaseGet(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BaseList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TemplatesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TemplateGet': grpc.unary_unary_rpc_method_handler(
          servicer.TemplateGet,
          request_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateGetRequest.FromString,
          response_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateGetResponse.SerializeToString,
      ),
      'TemplateList': grpc.unary_unary_rpc_method_handler(
          servicer.TemplateList,
          request_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateListRequest.FromString,
          response_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateListResponse.SerializeToString,
      ),
      'TemplateDelete': grpc.unary_unary_rpc_method_handler(
          servicer.TemplateDelete,
          request_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateDeleteRequest.FromString,
          response_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateDeleteResponse.SerializeToString,
      ),
      'TemplateUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.TemplateUpdate,
          request_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateUpdateRequest.FromString,
          response_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateUpdateResponse.SerializeToString,
      ),
      'TemplateFromDesktop': grpc.unary_unary_rpc_method_handler(
          servicer.TemplateFromDesktop,
          request_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateFromDesktopRequest.FromString,
          response_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.TemplateFromDesktopResponse.SerializeToString,
      ),
      'BaseGet': grpc.unary_unary_rpc_method_handler(
          servicer.BaseGet,
          request_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.BaseGetRequest.FromString,
          response_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.BaseGetResponse.SerializeToString,
      ),
      'BaseList': grpc.unary_unary_rpc_method_handler(
          servicer.BaseList,
          request_deserializer=engine_dot_grpc_dot_proto_dot_templates__pb2.BaseListRequest.FromString,
          response_serializer=engine_dot_grpc_dot_proto_dot_templates__pb2.BaseListResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'templates.Templates', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
