// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: pkg/proto/orchestrator.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetHyperRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gpu bool `protobuf:"varint,1,opt,name=gpu,proto3" json:"gpu,omitempty"`
}

func (x *GetHyperRequest) Reset() {
	*x = GetHyperRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_orchestrator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHyperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHyperRequest) ProtoMessage() {}

func (x *GetHyperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHyperRequest.ProtoReflect.Descriptor instead.
func (*GetHyperRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *GetHyperRequest) GetGpu() bool {
	if x != nil {
		return x.Gpu
	}
	return false
}

type GetHyperResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *GetHyperResponse) Reset() {
	*x = GetHyperResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_orchestrator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHyperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHyperResponse) ProtoMessage() {}

func (x *GetHyperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_orchestrator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHyperResponse.ProtoReflect.Descriptor instead.
func (*GetHyperResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *GetHyperResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_pkg_proto_orchestrator_proto protoreflect.FileDescriptor

var file_pkg_proto_orchestrator_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x63, 0x68,
	0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x48, 0x79, 0x70, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x70, 0x75, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x67, 0x70, 0x75, 0x22, 0x26, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x48, 0x79, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x32, 0x4d, 0x0a, 0x0c, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x3d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x48, 0x79, 0x70, 0x65, 0x72, 0x12, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x79, 0x70, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x48, 0x79, 0x70, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x69, 0x73, 0x61, 0x72, 0x64, 0x2d, 0x76, 0x64, 0x69, 0x2f, 0x69, 0x73, 0x61, 0x72, 0x64, 0x2f,
	0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_orchestrator_proto_rawDescOnce sync.Once
	file_pkg_proto_orchestrator_proto_rawDescData = file_pkg_proto_orchestrator_proto_rawDesc
)

func file_pkg_proto_orchestrator_proto_rawDescGZIP() []byte {
	file_pkg_proto_orchestrator_proto_rawDescOnce.Do(func() {
		file_pkg_proto_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_orchestrator_proto_rawDescData)
	})
	return file_pkg_proto_orchestrator_proto_rawDescData
}

var file_pkg_proto_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_orchestrator_proto_goTypes = []interface{}{
	(*GetHyperRequest)(nil),  // 0: proto.GetHyperRequest
	(*GetHyperResponse)(nil), // 1: proto.GetHyperResponse
}
var file_pkg_proto_orchestrator_proto_depIdxs = []int32{
	0, // 0: proto.Orchestrator.GetHyper:input_type -> proto.GetHyperRequest
	1, // 1: proto.Orchestrator.GetHyper:output_type -> proto.GetHyperResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_orchestrator_proto_init() }
func file_pkg_proto_orchestrator_proto_init() {
	if File_pkg_proto_orchestrator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_orchestrator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHyperRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_orchestrator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHyperResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_orchestrator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_orchestrator_proto_goTypes,
		DependencyIndexes: file_pkg_proto_orchestrator_proto_depIdxs,
		MessageInfos:      file_pkg_proto_orchestrator_proto_msgTypes,
	}.Build()
	File_pkg_proto_orchestrator_proto = out.File
	file_pkg_proto_orchestrator_proto_rawDesc = nil
	file_pkg_proto_orchestrator_proto_goTypes = nil
	file_pkg_proto_orchestrator_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrchestratorClient interface {
	GetHyper(ctx context.Context, in *GetHyperRequest, opts ...grpc.CallOption) (*GetHyperResponse, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) GetHyper(ctx context.Context, in *GetHyperRequest, opts ...grpc.CallOption) (*GetHyperResponse, error) {
	out := new(GetHyperResponse)
	err := c.cc.Invoke(ctx, "/proto.Orchestrator/GetHyper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServer is the server API for Orchestrator service.
type OrchestratorServer interface {
	GetHyper(context.Context, *GetHyperRequest) (*GetHyperResponse, error)
}

// UnimplementedOrchestratorServer can be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServer struct {
}

func (*UnimplementedOrchestratorServer) GetHyper(context.Context, *GetHyperRequest) (*GetHyperResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHyper not implemented")
}

func RegisterOrchestratorServer(s *grpc.Server, srv OrchestratorServer) {
	s.RegisterService(&_Orchestrator_serviceDesc, srv)
}

func _Orchestrator_GetHyper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHyperRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetHyper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Orchestrator/GetHyper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetHyper(ctx, req.(*GetHyperRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Orchestrator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHyper",
			Handler:    _Orchestrator_GetHyper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/orchestrator.proto",
}
