// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/isard.proto

package isard

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// DesktopState are all the different states that a desktop can be on
type DesktopState int32

const (
	DesktopState_STOPPED DesktopState = 0
	DesktopState_STARTED DesktopState = 1
	DesktopState_PAUSED  DesktopState = 2
	DesktopState_DELETED DesktopState = 3
	DesktopState_FAILED  DesktopState = 4
	DesktopState_UNKNOWN DesktopState = 5
)

var DesktopState_name = map[int32]string{
	0: "STOPPED",
	1: "STARTED",
	2: "PAUSED",
	3: "DELETED",
	4: "FAILED",
	5: "UNKNOWN",
}
var DesktopState_value = map[string]int32{
	"STOPPED": 0,
	"STARTED": 1,
	"PAUSED":  2,
	"DELETED": 3,
	"FAILED":  4,
	"UNKNOWN": 5,
}

func (x DesktopState) String() string {
	return proto.EnumName(DesktopState_name, int32(x))
}
func (DesktopState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{0}
}

// Permissions are the permissions of a resource
type Permissions struct {
	// public specifies if everyone has access the resource. If it's set to true, it's going to ignore the other fields
	Public bool `protobuf:"varint,1,opt,name=public,proto3" json:"public,omitempty"`
	// roles are the roles that have access to the resource
	Roles []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	// categories are the categories that have access to the resource
	Categories []string `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	// users are the users that have access to the resource
	Users                []string `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permissions) Reset()         { *m = Permissions{} }
func (m *Permissions) String() string { return proto.CompactTextString(m) }
func (*Permissions) ProtoMessage()    {}
func (*Permissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{0}
}
func (m *Permissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permissions.Unmarshal(m, b)
}
func (m *Permissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permissions.Marshal(b, m, deterministic)
}
func (dst *Permissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permissions.Merge(dst, src)
}
func (m *Permissions) XXX_Size() int {
	return xxx_messageInfo_Permissions.Size(m)
}
func (m *Permissions) XXX_DiscardUnknown() {
	xxx_messageInfo_Permissions.DiscardUnknown(m)
}

var xxx_messageInfo_Permissions proto.InternalMessageInfo

func (m *Permissions) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *Permissions) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Permissions) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Permissions) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

// DomainOptions are the different options that a domain can hae
type DomainOptions struct {
	Viewers *DomainOptions_Viewers `protobuf:"bytes,1,opt,name=viewers,proto3" json:"viewers,omitempty"`
	// server sets if the desktop is going to be stopped by the automatic jobs
	Server               bool     `protobuf:"varint,2,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainOptions) Reset()         { *m = DomainOptions{} }
func (m *DomainOptions) String() string { return proto.CompactTextString(m) }
func (*DomainOptions) ProtoMessage()    {}
func (*DomainOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{1}
}
func (m *DomainOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainOptions.Unmarshal(m, b)
}
func (m *DomainOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainOptions.Marshal(b, m, deterministic)
}
func (dst *DomainOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainOptions.Merge(dst, src)
}
func (m *DomainOptions) XXX_Size() int {
	return xxx_messageInfo_DomainOptions.Size(m)
}
func (m *DomainOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainOptions.DiscardUnknown(m)
}

var xxx_messageInfo_DomainOptions proto.InternalMessageInfo

func (m *DomainOptions) GetViewers() *DomainOptions_Viewers {
	if m != nil {
		return m.Viewers
	}
	return nil
}

func (m *DomainOptions) GetServer() bool {
	if m != nil {
		return m.Server
	}
	return false
}

// Viewers are the options related with the viewers
type DomainOptions_Viewers struct {
	Spice                *DomainOptions_Viewers_Spice `protobuf:"bytes,1,opt,name=spice,proto3" json:"spice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DomainOptions_Viewers) Reset()         { *m = DomainOptions_Viewers{} }
func (m *DomainOptions_Viewers) String() string { return proto.CompactTextString(m) }
func (*DomainOptions_Viewers) ProtoMessage()    {}
func (*DomainOptions_Viewers) Descriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{1, 0}
}
func (m *DomainOptions_Viewers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainOptions_Viewers.Unmarshal(m, b)
}
func (m *DomainOptions_Viewers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainOptions_Viewers.Marshal(b, m, deterministic)
}
func (dst *DomainOptions_Viewers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainOptions_Viewers.Merge(dst, src)
}
func (m *DomainOptions_Viewers) XXX_Size() int {
	return xxx_messageInfo_DomainOptions_Viewers.Size(m)
}
func (m *DomainOptions_Viewers) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainOptions_Viewers.DiscardUnknown(m)
}

var xxx_messageInfo_DomainOptions_Viewers proto.InternalMessageInfo

func (m *DomainOptions_Viewers) GetSpice() *DomainOptions_Viewers_Spice {
	if m != nil {
		return m.Spice
	}
	return nil
}

// Spice are the options related with the Spice viewer
type DomainOptions_Viewers_Spice struct {
	// fullscreen sets if the desktop is going to be opened in fullscreen
	Fullscreen           bool     `protobuf:"varint,1,opt,name=fullscreen,proto3" json:"fullscreen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DomainOptions_Viewers_Spice) Reset()         { *m = DomainOptions_Viewers_Spice{} }
func (m *DomainOptions_Viewers_Spice) String() string { return proto.CompactTextString(m) }
func (*DomainOptions_Viewers_Spice) ProtoMessage()    {}
func (*DomainOptions_Viewers_Spice) Descriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{1, 0, 0}
}
func (m *DomainOptions_Viewers_Spice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainOptions_Viewers_Spice.Unmarshal(m, b)
}
func (m *DomainOptions_Viewers_Spice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainOptions_Viewers_Spice.Marshal(b, m, deterministic)
}
func (dst *DomainOptions_Viewers_Spice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainOptions_Viewers_Spice.Merge(dst, src)
}
func (m *DomainOptions_Viewers_Spice) XXX_Size() int {
	return xxx_messageInfo_DomainOptions_Viewers_Spice.Size(m)
}
func (m *DomainOptions_Viewers_Spice) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainOptions_Viewers_Spice.DiscardUnknown(m)
}

var xxx_messageInfo_DomainOptions_Viewers_Spice proto.InternalMessageInfo

func (m *DomainOptions_Viewers_Spice) GetFullscreen() bool {
	if m != nil {
		return m.Fullscreen
	}
	return false
}

type Desktop struct {
	// id is the unique identifier of the domain. It's formed by "_{username}_{desktopName}"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the name of the desktop
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// description is the user description of the desktop
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// state is the current state of the desktop
	State DesktopState `protobuf:"varint,6,opt,name=state,proto3,enum=isard.DesktopState" json:"state,omitempty"`
	// detail shows messages in case there's an error doing an operation with the desktop
	Detail string `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	// user is the user that owns the desktop
	User string `protobuf:"bytes,11,opt,name=user,proto3" json:"user,omitempty"`
	// os is the Operative System of the desktop
	Os string `protobuf:"bytes,14,opt,name=os,proto3" json:"os,omitempty"`
	// options are the options of the desktop
	Options              *DomainOptions `protobuf:"bytes,18,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Desktop) Reset()         { *m = Desktop{} }
func (m *Desktop) String() string { return proto.CompactTextString(m) }
func (*Desktop) ProtoMessage()    {}
func (*Desktop) Descriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{2}
}
func (m *Desktop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Desktop.Unmarshal(m, b)
}
func (m *Desktop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Desktop.Marshal(b, m, deterministic)
}
func (dst *Desktop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Desktop.Merge(dst, src)
}
func (m *Desktop) XXX_Size() int {
	return xxx_messageInfo_Desktop.Size(m)
}
func (m *Desktop) XXX_DiscardUnknown() {
	xxx_messageInfo_Desktop.DiscardUnknown(m)
}

var xxx_messageInfo_Desktop proto.InternalMessageInfo

func (m *Desktop) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Desktop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Desktop) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Desktop) GetState() DesktopState {
	if m != nil {
		return m.State
	}
	return DesktopState_STOPPED
}

func (m *Desktop) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Desktop) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Desktop) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Desktop) GetOptions() *DomainOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type LoginLocalRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Usr                  string   `protobuf:"bytes,2,opt,name=usr,proto3" json:"usr,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginLocalRequest) Reset()         { *m = LoginLocalRequest{} }
func (m *LoginLocalRequest) String() string { return proto.CompactTextString(m) }
func (*LoginLocalRequest) ProtoMessage()    {}
func (*LoginLocalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{3}
}
func (m *LoginLocalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginLocalRequest.Unmarshal(m, b)
}
func (m *LoginLocalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginLocalRequest.Marshal(b, m, deterministic)
}
func (dst *LoginLocalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginLocalRequest.Merge(dst, src)
}
func (m *LoginLocalRequest) XXX_Size() int {
	return xxx_messageInfo_LoginLocalRequest.Size(m)
}
func (m *LoginLocalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginLocalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginLocalRequest proto.InternalMessageInfo

func (m *LoginLocalRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoginLocalRequest) GetUsr() string {
	if m != nil {
		return m.Usr
	}
	return ""
}

func (m *LoginLocalRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type LoginLocalResponse struct {
	Tkn                  string   `protobuf:"bytes,1,opt,name=tkn,proto3" json:"tkn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginLocalResponse) Reset()         { *m = LoginLocalResponse{} }
func (m *LoginLocalResponse) String() string { return proto.CompactTextString(m) }
func (*LoginLocalResponse) ProtoMessage()    {}
func (*LoginLocalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{4}
}
func (m *LoginLocalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginLocalResponse.Unmarshal(m, b)
}
func (m *LoginLocalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginLocalResponse.Marshal(b, m, deterministic)
}
func (dst *LoginLocalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginLocalResponse.Merge(dst, src)
}
func (m *LoginLocalResponse) XXX_Size() int {
	return xxx_messageInfo_LoginLocalResponse.Size(m)
}
func (m *LoginLocalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginLocalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginLocalResponse proto.InternalMessageInfo

func (m *LoginLocalResponse) GetTkn() string {
	if m != nil {
		return m.Tkn
	}
	return ""
}

type UserDesktopsGetRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDesktopsGetRequest) Reset()         { *m = UserDesktopsGetRequest{} }
func (m *UserDesktopsGetRequest) String() string { return proto.CompactTextString(m) }
func (*UserDesktopsGetRequest) ProtoMessage()    {}
func (*UserDesktopsGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{5}
}
func (m *UserDesktopsGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDesktopsGetRequest.Unmarshal(m, b)
}
func (m *UserDesktopsGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDesktopsGetRequest.Marshal(b, m, deterministic)
}
func (dst *UserDesktopsGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDesktopsGetRequest.Merge(dst, src)
}
func (m *UserDesktopsGetRequest) XXX_Size() int {
	return xxx_messageInfo_UserDesktopsGetRequest.Size(m)
}
func (m *UserDesktopsGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDesktopsGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserDesktopsGetRequest proto.InternalMessageInfo

func (m *UserDesktopsGetRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UserDesktopsGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserDesktopsGetResponse struct {
	Api                  string     `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Desktops             []*Desktop `protobuf:"bytes,2,rep,name=desktops,proto3" json:"desktops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserDesktopsGetResponse) Reset()         { *m = UserDesktopsGetResponse{} }
func (m *UserDesktopsGetResponse) String() string { return proto.CompactTextString(m) }
func (*UserDesktopsGetResponse) ProtoMessage()    {}
func (*UserDesktopsGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{6}
}
func (m *UserDesktopsGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDesktopsGetResponse.Unmarshal(m, b)
}
func (m *UserDesktopsGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDesktopsGetResponse.Marshal(b, m, deterministic)
}
func (dst *UserDesktopsGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDesktopsGetResponse.Merge(dst, src)
}
func (m *UserDesktopsGetResponse) XXX_Size() int {
	return xxx_messageInfo_UserDesktopsGetResponse.Size(m)
}
func (m *UserDesktopsGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDesktopsGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserDesktopsGetResponse proto.InternalMessageInfo

func (m *UserDesktopsGetResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UserDesktopsGetResponse) GetDesktops() []*Desktop {
	if m != nil {
		return m.Desktops
	}
	return nil
}

type DesktopStartRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DesktopStartRequest) Reset()         { *m = DesktopStartRequest{} }
func (m *DesktopStartRequest) String() string { return proto.CompactTextString(m) }
func (*DesktopStartRequest) ProtoMessage()    {}
func (*DesktopStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{7}
}
func (m *DesktopStartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesktopStartRequest.Unmarshal(m, b)
}
func (m *DesktopStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesktopStartRequest.Marshal(b, m, deterministic)
}
func (dst *DesktopStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesktopStartRequest.Merge(dst, src)
}
func (m *DesktopStartRequest) XXX_Size() int {
	return xxx_messageInfo_DesktopStartRequest.Size(m)
}
func (m *DesktopStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DesktopStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DesktopStartRequest proto.InternalMessageInfo

func (m *DesktopStartRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DesktopStartRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DesktopStartResponse struct {
	State                DesktopState `protobuf:"varint,1,opt,name=state,proto3,enum=isard.DesktopState" json:"state,omitempty"`
	NextActions          []string     `protobuf:"bytes,2,rep,name=next_actions,json=nextActions,proto3" json:"next_actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DesktopStartResponse) Reset()         { *m = DesktopStartResponse{} }
func (m *DesktopStartResponse) String() string { return proto.CompactTextString(m) }
func (*DesktopStartResponse) ProtoMessage()    {}
func (*DesktopStartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_isard_7bb89084a91ce1b6, []int{8}
}
func (m *DesktopStartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DesktopStartResponse.Unmarshal(m, b)
}
func (m *DesktopStartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DesktopStartResponse.Marshal(b, m, deterministic)
}
func (dst *DesktopStartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DesktopStartResponse.Merge(dst, src)
}
func (m *DesktopStartResponse) XXX_Size() int {
	return xxx_messageInfo_DesktopStartResponse.Size(m)
}
func (m *DesktopStartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DesktopStartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DesktopStartResponse proto.InternalMessageInfo

func (m *DesktopStartResponse) GetState() DesktopState {
	if m != nil {
		return m.State
	}
	return DesktopState_STOPPED
}

func (m *DesktopStartResponse) GetNextActions() []string {
	if m != nil {
		return m.NextActions
	}
	return nil
}

func init() {
	proto.RegisterType((*Permissions)(nil), "isard.Permissions")
	proto.RegisterType((*DomainOptions)(nil), "isard.DomainOptions")
	proto.RegisterType((*DomainOptions_Viewers)(nil), "isard.DomainOptions.Viewers")
	proto.RegisterType((*DomainOptions_Viewers_Spice)(nil), "isard.DomainOptions.Viewers.Spice")
	proto.RegisterType((*Desktop)(nil), "isard.Desktop")
	proto.RegisterType((*LoginLocalRequest)(nil), "isard.LoginLocalRequest")
	proto.RegisterType((*LoginLocalResponse)(nil), "isard.LoginLocalResponse")
	proto.RegisterType((*UserDesktopsGetRequest)(nil), "isard.UserDesktopsGetRequest")
	proto.RegisterType((*UserDesktopsGetResponse)(nil), "isard.UserDesktopsGetResponse")
	proto.RegisterType((*DesktopStartRequest)(nil), "isard.DesktopStartRequest")
	proto.RegisterType((*DesktopStartResponse)(nil), "isard.DesktopStartResponse")
	proto.RegisterEnum("isard.DesktopState", DesktopState_name, DesktopState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IsardClient is the client API for Isard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IsardClient interface {
	// LoginLocal logs in the user using the local database and returns the token
	LoginLocal(ctx context.Context, in *LoginLocalRequest, opts ...grpc.CallOption) (*LoginLocalResponse, error)
	// UserDesktopsGet returns a list with all the desktops of an user
	UserDesktopsGet(ctx context.Context, in *UserDesktopsGetRequest, opts ...grpc.CallOption) (*UserDesktopsGetResponse, error)
	// DesktopStart starts a desktop by ID
	DesktopStart(ctx context.Context, in *DesktopStartRequest, opts ...grpc.CallOption) (*DesktopStartResponse, error)
}

type isardClient struct {
	cc *grpc.ClientConn
}

func NewIsardClient(cc *grpc.ClientConn) IsardClient {
	return &isardClient{cc}
}

func (c *isardClient) LoginLocal(ctx context.Context, in *LoginLocalRequest, opts ...grpc.CallOption) (*LoginLocalResponse, error) {
	out := new(LoginLocalResponse)
	err := c.cc.Invoke(ctx, "/isard.Isard/LoginLocal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isardClient) UserDesktopsGet(ctx context.Context, in *UserDesktopsGetRequest, opts ...grpc.CallOption) (*UserDesktopsGetResponse, error) {
	out := new(UserDesktopsGetResponse)
	err := c.cc.Invoke(ctx, "/isard.Isard/UserDesktopsGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isardClient) DesktopStart(ctx context.Context, in *DesktopStartRequest, opts ...grpc.CallOption) (*DesktopStartResponse, error) {
	out := new(DesktopStartResponse)
	err := c.cc.Invoke(ctx, "/isard.Isard/DesktopStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IsardServer is the server API for Isard service.
type IsardServer interface {
	// LoginLocal logs in the user using the local database and returns the token
	LoginLocal(context.Context, *LoginLocalRequest) (*LoginLocalResponse, error)
	// UserDesktopsGet returns a list with all the desktops of an user
	UserDesktopsGet(context.Context, *UserDesktopsGetRequest) (*UserDesktopsGetResponse, error)
	// DesktopStart starts a desktop by ID
	DesktopStart(context.Context, *DesktopStartRequest) (*DesktopStartResponse, error)
}

func RegisterIsardServer(s *grpc.Server, srv IsardServer) {
	s.RegisterService(&_Isard_serviceDesc, srv)
}

func _Isard_LoginLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsardServer).LoginLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isard.Isard/LoginLocal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsardServer).LoginLocal(ctx, req.(*LoginLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Isard_UserDesktopsGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDesktopsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsardServer).UserDesktopsGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isard.Isard/UserDesktopsGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsardServer).UserDesktopsGet(ctx, req.(*UserDesktopsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Isard_DesktopStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesktopStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsardServer).DesktopStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/isard.Isard/DesktopStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsardServer).DesktopStart(ctx, req.(*DesktopStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Isard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "isard.Isard",
	HandlerType: (*IsardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginLocal",
			Handler:    _Isard_LoginLocal_Handler,
		},
		{
			MethodName: "UserDesktopsGet",
			Handler:    _Isard_UserDesktopsGet_Handler,
		},
		{
			MethodName: "DesktopStart",
			Handler:    _Isard_DesktopStart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/isard.proto",
}

func init() { proto.RegisterFile("proto/isard.proto", fileDescriptor_isard_7bb89084a91ce1b6) }

var fileDescriptor_isard_7bb89084a91ce1b6 = []byte{
	// 840 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5f, 0x6f, 0xdb, 0x54,
	0x14, 0xc7, 0x4e, 0xd3, 0xb4, 0x27, 0xa5, 0x4b, 0xef, 0xaa, 0x62, 0xbc, 0x51, 0x65, 0x7e, 0x80,
	0x12, 0xd1, 0x78, 0xcb, 0xa4, 0x81, 0xf2, 0x84, 0x99, 0xcd, 0x14, 0x11, 0xb5, 0x91, 0xb3, 0x6e,
	0x12, 0x12, 0x42, 0x8e, 0x7d, 0xe7, 0xdd, 0xd5, 0xf1, 0xf5, 0xee, 0xbd, 0x49, 0x91, 0x10, 0x2f,
	0x7c, 0x04, 0x78, 0xe4, 0xeb, 0xc0, 0x03, 0x0f, 0x3c, 0xf1, 0x15, 0x10, 0x9f, 0x03, 0xdd, 0x3f,
	0x69, 0xd3, 0x25, 0xa3, 0xda, 0x53, 0xce, 0x39, 0xbf, 0xdf, 0x39, 0xbf, 0xf3, 0xe7, 0x46, 0x86,
	0xbd, 0x8a, 0x51, 0x41, 0x7d, 0xc2, 0x13, 0x96, 0x75, 0x95, 0x8d, 0xea, 0xca, 0x71, 0xef, 0xe6,
	0x94, 0xe6, 0x05, 0xf6, 0x93, 0x8a, 0xf8, 0x49, 0x59, 0x52, 0x91, 0x08, 0x42, 0x4b, 0xae, 0x49,
	0xee, 0x67, 0xea, 0x27, 0x3d, 0xce, 0x71, 0x79, 0xcc, 0x2f, 0x92, 0x3c, 0xc7, 0xcc, 0xa7, 0x95,
	0x62, 0xac, 0xb2, 0xbd, 0xd7, 0xd0, 0x1c, 0x61, 0x36, 0x25, 0x9c, 0xcb, 0x20, 0x3a, 0x80, 0xcd,
	0x6a, 0x36, 0x29, 0x48, 0xea, 0x58, 0x6d, 0xeb, 0x68, 0x2b, 0x36, 0x1e, 0xda, 0x87, 0x3a, 0xa3,
	0x05, 0xe6, 0x8e, 0xdd, 0xae, 0x1d, 0x6d, 0xc7, 0xda, 0x41, 0x87, 0x00, 0x69, 0x22, 0x70, 0x4e,
	0x19, 0xc1, 0xdc, 0xa9, 0x29, 0x68, 0x29, 0x22, 0xb3, 0x66, 0x1c, 0x33, 0xee, 0x6c, 0xe8, 0x2c,
	0xe5, 0x78, 0x7f, 0x59, 0xf0, 0x7e, 0x48, 0xa7, 0x09, 0x29, 0x4f, 0x75, 0x5b, 0xe8, 0x11, 0x34,
	0xe6, 0x04, 0x5f, 0x48, 0xa6, 0x94, 0x6d, 0xf6, 0xee, 0x76, 0xf5, 0xd8, 0xd7, 0x68, 0xdd, 0x67,
	0x9a, 0x13, 0x2f, 0xc8, 0xb2, 0x5b, 0x8e, 0xd9, 0x1c, 0x33, 0xc7, 0xd6, 0xdd, 0x6a, 0xcf, 0x2d,
	0xa0, 0x61, 0xb8, 0xe8, 0x0b, 0xa8, 0xf3, 0x8a, 0xa4, 0xd8, 0x14, 0xf6, 0xfe, 0xaf, 0x70, 0x77,
	0x2c, 0x99, 0xb1, 0x4e, 0x70, 0x3f, 0x81, 0xba, 0xf2, 0xe5, 0x94, 0x2f, 0x66, 0x45, 0xc1, 0x53,
	0x86, 0x71, 0x69, 0xf6, 0xb2, 0x14, 0xf1, 0xfe, 0xb5, 0xa0, 0x11, 0x62, 0x7e, 0x2e, 0x68, 0x85,
	0x76, 0xc1, 0x26, 0x99, 0xe2, 0x6c, 0xc7, 0x36, 0xc9, 0x10, 0x82, 0x8d, 0x32, 0x99, 0x62, 0xd5,
	0xdf, 0x76, 0xac, 0x6c, 0xd4, 0x86, 0x66, 0x86, 0x79, 0xca, 0x88, 0x52, 0x77, 0x6a, 0x0a, 0x5a,
	0x0e, 0xa1, 0x4f, 0xa1, 0xce, 0x45, 0x22, 0xb0, 0xb3, 0xd9, 0xb6, 0x8e, 0x76, 0x7b, 0xb7, 0x17,
	0x4d, 0x6b, 0x91, 0xb1, 0x84, 0x62, 0xcd, 0x90, 0x2b, 0xc8, 0xb0, 0x48, 0x48, 0xe1, 0x34, 0x54,
	0x1d, 0xe3, 0x49, 0x61, 0xb9, 0x6d, 0xa7, 0xa9, 0x85, 0xa5, 0x2d, 0x9b, 0xa3, 0xdc, 0xd9, 0xd5,
	0xcd, 0x51, 0x8e, 0xba, 0xd0, 0x30, 0x0f, 0xc3, 0x41, 0x6a, 0x3b, 0xfb, 0xeb, 0xb6, 0x13, 0x2f,
	0x48, 0xde, 0x00, 0xf6, 0x86, 0x34, 0x27, 0xe5, 0x90, 0xa6, 0x49, 0x11, 0xe3, 0xd7, 0x33, 0xcc,
	0x05, 0x6a, 0x41, 0x2d, 0xa9, 0x88, 0x19, 0x59, 0x9a, 0x32, 0x32, 0xe3, 0xcc, 0x8c, 0x2c, 0x4d,
	0x19, 0xa9, 0x2e, 0x32, 0x33, 0xa9, 0x34, 0xbd, 0x8f, 0x01, 0x2d, 0x97, 0xe2, 0x15, 0x2d, 0x39,
	0x96, 0x3c, 0x71, 0x5e, 0x2e, 0x6a, 0x89, 0xf3, 0xd2, 0xeb, 0xc3, 0xc1, 0x19, 0xc7, 0xcc, 0x4c,
	0xce, 0x9f, 0x60, 0xf1, 0x76, 0x5d, 0xbd, 0x7b, 0x7b, 0xb1, 0x7b, 0xef, 0x39, 0x7c, 0xb0, 0x92,
	0x7b, 0x25, 0xf4, 0x46, 0x72, 0x07, 0xb6, 0x32, 0x43, 0x54, 0x6f, 0xbc, 0xd9, 0xdb, 0xbd, 0xbe,
	0xf5, 0xf8, 0x12, 0xf7, 0x3e, 0x87, 0xdb, 0x57, 0xa7, 0x60, 0xef, 0xd0, 0x51, 0x06, 0xfb, 0xd7,
	0x13, 0x4d, 0x3b, 0x97, 0xf7, 0xb6, 0x6e, 0xbc, 0xf7, 0x3d, 0xd8, 0x29, 0xf1, 0x0f, 0xe2, 0xfb,
	0x24, 0xd5, 0x87, 0xd3, 0xff, 0xc7, 0xa6, 0x8c, 0x05, 0x3a, 0xd4, 0xf9, 0x16, 0x76, 0x96, 0x33,
	0x51, 0x13, 0x1a, 0xe3, 0xa7, 0xa7, 0xa3, 0x51, 0x14, 0xb6, 0xde, 0xd3, 0x4e, 0x10, 0x3f, 0x8d,
	0xc2, 0x96, 0x85, 0x00, 0x36, 0x47, 0xc1, 0xd9, 0x38, 0x0a, 0x5b, 0xb6, 0x04, 0xc2, 0x68, 0x18,
	0x49, 0xa0, 0x26, 0x81, 0xaf, 0x83, 0xc1, 0x30, 0x0a, 0x5b, 0x1b, 0x12, 0x38, 0x3b, 0xf9, 0xe6,
	0xe4, 0xf4, 0xf9, 0x49, 0xab, 0xde, 0xfb, 0xdd, 0x86, 0xfa, 0x40, 0x36, 0x87, 0xbe, 0x03, 0xb8,
	0xba, 0x20, 0x72, 0x4c, 0xcb, 0x2b, 0xef, 0xc3, 0xfd, 0x70, 0x0d, 0xa2, 0xc7, 0xf6, 0xdc, 0x9f,
	0xff, 0xfe, 0xe7, 0x57, 0x7b, 0xdf, 0xbb, 0xe5, 0xcf, 0x1f, 0xf8, 0x85, 0xc4, 0xfd, 0x42, 0x12,
	0xfa, 0x56, 0x07, 0x55, 0x70, 0xeb, 0x8d, 0xe3, 0xa1, 0x8f, 0x4c, 0xa5, 0xf5, 0x0f, 0xc2, 0x3d,
	0x7c, 0x1b, 0x6c, 0xd4, 0x0e, 0x95, 0x9a, 0x83, 0x0e, 0xa4, 0x9a, 0xfc, 0x3f, 0xf8, 0x3f, 0x92,
	0xec, 0x27, 0x7f, 0x71, 0x55, 0xf4, 0x6a, 0x79, 0x6d, 0x4c, 0x20, 0x77, 0xe5, 0x0a, 0x97, 0xa7,
	0x76, 0xef, 0xac, 0xc5, 0x8c, 0xd0, 0x3d, 0x25, 0x74, 0xc7, 0x53, 0x42, 0xa6, 0xbc, 0xd6, 0xe2,
	0x92, 0xd7, 0xb7, 0x3a, 0x5f, 0xfd, 0x69, 0xfd, 0x12, 0xfc, 0x61, 0xa1, 0xdf, 0x2c, 0xd8, 0x51,
	0xdb, 0x7c, 0x16, 0x0e, 0xda, 0xc1, 0x68, 0xe0, 0x05, 0xb0, 0xb5, 0xf0, 0x91, 0xf7, 0x52, 0x88,
	0x8a, 0xf7, 0x7d, 0x3f, 0x27, 0xe2, 0xe5, 0x6c, 0xd2, 0x4d, 0xe9, 0x54, 0x7f, 0x0c, 0x8e, 0xe7,
	0x19, 0xd1, 0x96, 0xbb, 0x47, 0xca, 0x17, 0xf4, 0x4b, 0x65, 0xcf, 0x33, 0x22, 0x29, 0x9d, 0xc7,
	0xb0, 0x1d, 0x3c, 0x19, 0x0d, 0xdb, 0xf3, 0x87, 0xdd, 0xfb, 0xe8, 0xd1, 0xcd, 0x35, 0xfc, 0x49,
	0x41, 0x27, 0xfe, 0x34, 0xe1, 0x02, 0x33, 0x7f, 0x38, 0x78, 0x1c, 0x9d, 0x8c, 0xa3, 0x5e, 0xed,
	0x41, 0xf7, 0x7e, 0xc7, 0xb2, 0x7b, 0xad, 0xa4, 0xaa, 0x0a, 0x92, 0xaa, 0x2f, 0x86, 0xff, 0x8a,
	0xd3, 0xb2, 0xbf, 0x12, 0x99, 0x6c, 0xaa, 0x0f, 0xc9, 0xc3, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x26, 0x3c, 0xc9, 0x56, 0xb0, 0x06, 0x00, 0x00,
}
