# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from api.grpc.proto import desktops_stream_pb2 as api_dot_grpc_dot_proto_dot_desktops__stream__pb2


class DesktopsStreamStub(object):
  """import "google/protobuf/empty.proto"; 
  import "google/protobuf/any.proto";

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Changes = channel.unary_stream(
        '/desktops_stream.DesktopsStream/Changes',
        request_serializer=api_dot_grpc_dot_proto_dot_desktops__stream__pb2.DesktopsStreamRequest.SerializeToString,
        response_deserializer=api_dot_grpc_dot_proto_dot_desktops__stream__pb2.DesktopsStreamResponse.FromString,
        )


class DesktopsStreamServicer(object):
  """import "google/protobuf/empty.proto"; 
  import "google/protobuf/any.proto";

  """

  def Changes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DesktopsStreamServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Changes': grpc.unary_stream_rpc_method_handler(
          servicer.Changes,
          request_deserializer=api_dot_grpc_dot_proto_dot_desktops__stream__pb2.DesktopsStreamRequest.FromString,
          response_serializer=api_dot_grpc_dot_proto_dot_desktops__stream__pb2.DesktopsStreamResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'desktops_stream.DesktopsStream', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
