# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from api.grpc.proto import templates_stream_pb2 as api_dot_grpc_dot_proto_dot_templates__stream__pb2


class TemplatesStreamStub(object):
  """import "google/protobuf/empty.proto"; 
  import "google/protobuf/any.proto";

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Changes = channel.unary_stream(
        '/templates_stream.TemplatesStream/Changes',
        request_serializer=api_dot_grpc_dot_proto_dot_templates__stream__pb2.StreamRequest.SerializeToString,
        response_deserializer=api_dot_grpc_dot_proto_dot_templates__stream__pb2.StreamResponse.FromString,
        )


class TemplatesStreamServicer(object):
  """import "google/protobuf/empty.proto"; 
  import "google/protobuf/any.proto";

  """

  def Changes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TemplatesStreamServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Changes': grpc.unary_stream_rpc_method_handler(
          servicer.Changes,
          request_deserializer=api_dot_grpc_dot_proto_dot_templates__stream__pb2.StreamRequest.FromString,
          response_serializer=api_dot_grpc_dot_proto_dot_templates__stream__pb2.StreamResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'templates_stream.TemplatesStream', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
